name: uxr_api
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - acres==0.2.0
      - annotated-types==0.7.0
      - anyio==4.7.0
      - astroid==3.3.8
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - ci-info==0.3.0
      - click==8.1.8
      - configobj==5.0.9
      - configparser==7.1.0
      - dill==0.3.9
      - distro==1.9.0
      - dnspython==2.7.0
      - docx==0.2.4
      - etelemetry==0.3.1
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - filelock==3.16.1
      - fitz==0.0.1.dev2
      - h11==0.14.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - idna==3.10
      - importlib-resources==6.4.5
      - isodate==0.6.1
      - isort==5.13.2
      - jiter==0.8.2
      - looseversion==1.3.0
      - lxml==5.3.0
      - mccabe==0.7.0
      - mypy-extensions==1.0.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - nipype==1.9.2
      - numpy==2.2.1
      - openai==1.58.1
      - packaging==24.2
      - pandas==2.2.3
      - pathlib==1.0.1
      - pathspec==0.12.1
      - pillow==11.1.0
      - platformdirs==4.3.6
      - prov==2.0.1
      - puremagic==1.28
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydot==3.0.3
      - pymongo==4.10.1
      - pymupdf==1.25.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyxnat==1.6.2
      - rdflib==6.3.2
      - requests==2.32.3
      - scipy==1.14.1
      - simplejson==3.19.3
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.41.3
      - tomli==2.2.1
      - tomlkit==0.13.2
      - tqdm==4.67.1
      - traits==6.4.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
